/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CloudflareR2Upload: typeof import('./src/components/CloudflareR2Upload.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NLoadingBarProvide: typeof import('naive-ui')['NLoadingBarProvide']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NLog: typeof import('naive-ui')['NLog']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseVirtualList: typeof import('@vueuse/components')['UseVirtualList']
  }
}
